---
title: "SLICER Code"
output: html_notebook
author: "Reha Mathur" 
---

```{r}
# loading in SLICER packages
library("devtools")
install_github("jw156605/SLICER")
library(SLICER)
library(lle)
```


```{r}
# finding the number of initial clusters for reconstructing the trajectory
k = select_k(top_genes, kmin = 3)
```
```{r}
# performing LLE a form of dimensionality reduction on the gene expression data
# m = 3 bc that is the number of dimensions used in the figures in the paper 
traj_lle = lle(top_genes, m=3, k)$Y
```


```{r}
# build a knearest neighbor graph to find the distances betwen cells
traj_graph = conn_knn_graph(traj_lle, k)
```
```{r}
# constructing the cell order and finding branches in the trajectory 
ends = find_extreme_cells(traj_graph, traj_lle)
start = 402 # needs to be changed to a known cardiac fibroblast 
cells_ordered = cell_order(traj_graph, start)
graph_process_distance(traj_graph,traj_lle,start)
```


```{r}
distances_inactive = process_distance(traj_graph, 402) / 5.241427
distances_active = process_distance(traj_graph, 346) / 9.541308

```

```{r}
library(rgl)
library(plotly)
```


```{r}

active_cells
top_genes_test = as.data.frame(top_genes)
top_genes_test$row_number = 1:nrow(top_genes_test)
active_cell_numbers = top_genes_test[active_cells,401]

lle_df = data.frame(traj_lle )
lle_df$pseudotime = as.double(t(distances_inactive))
lle_df$active = "CCI"
lle_df[active_cell_numbers,4] = as.double(t(distances_active))[active_cell_numbers]
lle_df[active_cell_numbers,5] = "CCA"
lle_df$active = as.factor(lle_df$active)
lle_df$ident = identified_cells$GroupID_Fig1a
lle_df$ident_2 = cell_categorized$stage

```


```{r}

axx <- list(
  title = "LLE 1"
)

axy <- list(
  title = "LLE 2"
)

axz <- list(
  title = "LLE 3"
)

t <- list(
  size = 16,
  color = "black")

fig <- plot_ly(lle_df, x = ~X1, y = ~X2, z = ~X3, marker = list(size = 6), symbol = ~active, symbols = c("diamond", "circle") )
fig <- fig %>% add_markers(color = ~pseudotime, colors = c('black', 'red', 'orange', 'yellow'))
fig <- fig %>% layout(scene = list(aspectmode = "cube", xaxis=axx,yaxis=axy,zaxis=axz), font = t)

fig
```
```{r}
inactive_cell_rows = !(1:nrow(lle_df)  %in% active_cell_numbers )
lle_df[inactive_cell_rows,]
```



```{r}
axx <- list(
  title = "LLE 1"
)

axy <- list(
  title = "LLE 2"
)

axz <- list(
  title = "LLE 3"
)

t <- list(
  size = 16,
  color = "black")

fig <- plot_ly(lle_df, x = ~X1, y = ~X2, z = ~X3, color = ~ident_2, marker = list(size = 6), symbol = ~active, symbols = c("diamond", "circle") )
fig <- fig %>% add_markers(colors = c('blue', 'red', 'purple', 'lightgreen'))
fig <- fig %>% layout(scene = list(aspectmode = "cube", xaxis=axx,yaxis=axy,zaxis=axz), font = t)
fig
```





